version: 2
jobs:
  build:
    working_directory: ~/blog-hakyll
    machine: true
    branches:
      only:
        - develop
    steps:
      - checkout
      - run:
          name: get code
          command: |
            # git clone https://github.com/kaychaks/kaychaks.github.io.git ~/blog-hakyll
            git config --global user.email robots@circleci.com
            git config --global user.name CircleCI
            git fetch --force origin "master:remotes/origin/master"
            git checkout -q -B master
            git reset --hard origin/master
            git checkout develop
      - run:
          name: setup nix & get dependencies
          command: |
            bash <(curl https://nixos.org/nix/install)
            mkdir --parents /home/circleci/.config/nixpkgs; mv config.nix $_
      # - restore_cache:
      #     keys:
      #       - deps1-{{.Branch}}-{{ checksum "blog-hakyll.cabal" }}
      # - run:
      #     name: setup haskell
      #     command: |
      #       source /home/circleci/.nix-profile/etc/profile.d/nix.sh
      #       nix-env -iA nixpkgs.haskellPackages.cabal-install
      #       nix-shell --run exit
      - run:
          name: build project
          command: |
            source /home/circleci/.nix-profile/etc/profile.d/nix.sh
            nix-shell --packages "haskellPackages.ghcWithPackages (p: [p.cabal-install])" --run "cabal new-build"
      # - save_cache:
      #     key: deps1-{{.Branch}}-{{ checksum "blog-hakyll.cabal" }}
      #     paths:
      #       - "/nix"
      - deploy:
          name: deploy master to github pages
          command: |
            source /home/circleci/.nix-profile/etc/profile.d/nix.sh
            git config --global user.email robots@circleci.com
            git config --global user.name CircleCI
            nix-shell --run "cabal new-run site -- clean"
            nix-shell --run "cabal new-run site -- build"
            git checkout master
            echo "Overwrite existing files with new files"
            cp -a _site/. .
            echo "Commit"
            git add --all
            git commit -m "[`date '+%F %T %Z'`] Update"
            git push origin master:master
