version: 2
jobs:
  build:
    working_directory: ~/blog-hakyll
    machine: true
    branches:
      only:
        - develop
    steps:
      - checkout
      - run:
          name: setup nix & get dependencies
          command: |
            bash <(curl https://nixos.org/nix/install)
            source /home/circleci/.nix-profile/etc/profile.d/nix.sh
            nix-env -iA nixpkgs.haskellPackages.cabal-install
            nix-shell --run exit
      - run:
          name: build project
          command: |
            source /home/circleci/.nix-profile/etc/profile.d/nix.sh
            nix-shell --run "cabal new-build"
      - deploy:
          name: deploy master to github pages
          command: |
            source /home/circleci/.nix-profile/etc/profile.d/nix.sh
            git config --global user.email robots@circleci.com
            git config --global user.name CircleCI
            nix-shell --run "cabal new-run site -- clean"
            nix-shell --run "cabal new-run site -- build"
            git fetch --all
            git checkout master
            echo "Overwrite existing files with new files"
            cp -a _site/. .
            echo "Commit"
            git add --all
            git commit -m "[`date '+%F %T %Z'`] New Post"
            git push origin master:master
