name: CI Workflow
on:
  push:
    branches:
      - "develop"
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc:
          - 8.10.7
        cabal:
          - 3.6.2.0

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: "cache setup"
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}
      - name: "build deps"
        run: |
          cabal update
          cabal build --only-dependencies
      - name: "build site"
        run: |
          cabal build
          cabal exec site build
       
      - name: "deploy"
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/develop' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static
          publish_branch: master
          
