name: CI Workflow

on:
  push:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            accept-flake-config = true
            experimental-features = nix-command flakes

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: kaushikc-blog
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build site
        run: nix build --print-build-logs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: result/

  deploy:
    needs: build
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
