name: Blog Workflow

on:
  push:
    branches: [develop]

jobs:
  cabal:
    name:  ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cabal: ["3.2"]
        ghc:
          - "8.8.4"
    steps:
      - uses: actions/checkout@v2
        if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/develop'

      - name: Setup Haskell
        uses: actions/setup-haskell@v1.1.4
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      
      - name: Configure
        run: |
          cabal configure
      
      - name: Freeze
        run: |
          cabal freeze

      - name: Cache ~/.cabal/store
        uses: actions/cache@v2.1.3
        with:
          path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

      - name: Install dependencies
        run: |
          cabal build all --only-dependencies
      
      - name: Build
        run: |
          cabal build all

      - name: Checkout Master
        uses: actions/checkout@v2
        with:
          ref: "master"
          clean: "false"

      - name: Copy site
        run: cp -a site/. .

      - name: Git add
        run: |
          git add --all

      - name: Git config
        run: |
          git config --global user.email $GITHUB_ACTOR@users.noreply.github.com
          git config --global user.name $GITHUB_ACTOR

      - name: Git commit
        run: git commit -m "[`date '+%F %T %Z'`] Update"

      - name: Git push
        run: git push origin master:master
